export const employees = [
    {
      id: 0,
      user: "Chelsie Haley",
      login: "@username",
      avatar: "profile_icon",
      email: "chelsie@ui8.net",
      level: 4,
    },
    {
      id: 1,
      user: "Filomena Fahey",
      login: "@username",
      avatar: "profile_icon",
      email: "fahey.designer@robot.co",
      level: 6,
    },
    {
      id: 2,
      user: "Orion Luettgen",
      login: "@username",
      avatar: "profile_icon",
      email: "orion88@yahoo.com",
      level: 28,
    },
    {
      id: 3,
      user: "Brown Beatty",
      login: "@username",
      avatar: "profile_icon",
      email: "brown.be@gmail.com",
      level: 42,
    },
    {
      id: 4,
      user: "Bessie Runolfsson",
      login: "@username",
      avatar: "profile_icon",
      email: "bess@ui8.net",
      level: 42,
    },
    {
      id: 5,
      user: "Chelsie Haley",
      login: "@username",
      avatar: "profile_icon",
      email: "chelsie@ui8.net",
      level: 16,
    },
    {
      id: 6,
      user: "Filomena Fahey",
      login: "@username",
      avatar: "profile_icon",
      email: "fahey.designer@robot.co",
      level: 6,
    },
    {
      id: 7,
      user: "Orion Luettgen",
      login: "@username",
      avatar: "profile_icon",
      email: "orion88@yahoo.com",
      level: 28,
    },
    {
      id: 8,
      user: "Brown Beatty",
      login: "@username",
      avatar: "profile_icon",
      email: "brown.be@gmail.com",
      level: 42,
    },
    {
      id: 9,
      user: "Bessie Runolfsson",
      login: "@username",
      avatar: "profile_icon",
      email: "bess@ui8.net",
      level:  42,
    },
  ];
  